AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 2.3
  Exclude:
    - lib/generators/audited/templates/**/*
    - vendor/bundle/**/*
    - gemfiles/vendor/bundle/**/*

Bundler/OrderedGems:
  Enabled: false

Gemspec/OrderedDependencies:
  Enabled: false

Layout:
  Enabled: false

Metrics:
  Enabled: false

Naming:
  Enabled: false

Style:
  Enabled: false
