version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2

jobs:
  build:
    docker:
      - image: circleci/ruby:2.3-stretch
    executor: ruby/default
    steps:
      - checkout
      - ruby/bundle-install
      - run:
          name: rspec
          command: bundle exec rspec