FROM mcr.microsoft.com/vscode/devcontainers/ruby:3.2

RUN sudo gem update --system 
RUN gem install appraisal
RUN sudo chown -R vscode:vscode /usr/local/rvm/gems /usr/local/rvm/gems/default /usr/local/lib/ruby /usr/local/bundle