name: CI

on:
  - pull_request
  - push

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby: [2.7, 3.0, 3.1, 3.2]
        appraisal:
          - rails60
          - rails61
          - rails70
        db: [POSTGRES, MYSQL, SQLITE]
        exclude:
          # Rails 6.0 supports Ruby 2.5-2.7
          - appraisal: rails60
            ruby: 3.0
          - appraisal: rails60
            ruby: 3.1
          - appraisal: rails60
            ruby: 3.2

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: audited_test
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    env:
      DB_DATABASE: audited_test
      DB_USER: root
      DB_PASSWORD: 'root'
      DB_HOST: localhost

    steps:
    - name: Setup MySQL
      run: |
        sudo /etc/init.d/mysql start
        mysql -e 'CREATE DATABASE audited_test;' -uroot -proot
        mysql -e 'SHOW DATABASES;' -uroot -proot
    - uses: actions/checkout@v3
    - name: Copy Gemfile
      run: sed 's/\.\././' gemfiles/${{ matrix.appraisal }}.gemfile > Gemfile
    - name: Set up Ruby ${{ matrix.ruby }}
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Run tests
      env:
        DB: ${{ matrix.db }}
      run: bundle exec rake
